# Generated by Django 2.0.3 on 2018-04-04 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='UserModel',
        ),
    ]
