# Generated by Django 2.0.3 on 2018-04-04 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_auto_20180404_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='name',
        ),
    ]
