# Generated by Django 2.0.3 on 2018-04-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0003_remove_usermodel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='data',
            new_name='name',
        ),
    ]
