# Generated by Django 2.0.3 on 2018-04-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0004_auto_20180404_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='name',
            new_name='data',
        ),
    ]
